steps:

# This installs all the dependencies
- name: 'python'
  args: ['pip3','install', '-r', 'requirements.txt', '--user']

# Run all unit tests
- name: 'python'
  args: ['python3','pytest', '-v'] 

# Build docker container from the code via GitHub Repo
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/latitude-app', '.']
  
# Push container to container registry - Google artifact registry
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/latitude-app']
  
#deploy to cloud run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'cloudrunservice'
  - '--image'
  - 'gcr.io/$PROJECT_ID/latitude-app'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
images:
  - 'gcr.io/$PROJECT_ID/latitude-app'
